global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'url-shortener-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:


scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'url-shortener'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['url-shortener:8080']
        labels:
          application: 'url-shortener'
          environment: 'docker'